import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { Urbanist } from 'next/font/google'

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${urbanist.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body suppressHydrationWarning>
        <Header />
        <div className="pt-[140px] md:pt-[162px]">
          {children}
        </div>
      </body>
    </html>
  );
}
